### ISSUE TITLE
Baseline model for logical reasoning

### ISSUE THREAD

**Issue by SparkJiao** [LogiTorch/logitorch#2]
Hi, very appreciate your contribution to the research of logical reasoning!

We also have a strong [baseline system](https://github.com/SparkJiao/MERIt) for logical reasoning. The model is easy to use since the architecture is the same to conventional BERT/RoBERTa/DeBERTa/ALBERT and we also provide the code and data for pre-training for your reference. Would you like to incorporate it to your tools?

Let me know if you have any questions and thank you very much!

**Comment by ChadiHelwe** [comment]
Hello SparkJio,

Thank you for having an interest in LogiTorch. Yes, I will add it! I will modify the ReadME and adds MERIT to include it in future releases.

**Comment by SparkJiao** [comment]
Thanks for your help very much!
