### ISSUE TITLE
ModuleNotFoundError: No module named 'logitorch'

### ISSUE THREAD

**Issue by ke-lara** [LogiTorch/logitorch#3]
After successful pip install, I tried the pipeline example but got this: 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[7], line 1
----> 1 from logitorch.pipelines.proof_qa_pipelines import ruletaker_pipeline
      2 from logitorch.pl_models.ruletaker import PLRuleTaker
      4 model = PLRuleTaker(learning_rate=1e-5, weight_decay=0.1)

ModuleNotFoundError: No module named 'logitorch'

**Comment by ChadiHelwe** [comment]
Can you tell me which Python version you are using and which OS?

**Comment by ke-lara** [comment]
Python 3.7 on Ubuntu. Could it be some lib path settings issue ?

**Comment by ChadiHelwe** [comment]
Fixed

**Comment by ke-lara** [comment]
Still facing the issue. What's the fix?

**Comment by ChadiHelwe** [comment]
Did you install it from GitHub? I still didn't upload a new version on Pypi

**Comment by ke-lara** [comment]
> Did you install it from GitHub? I still didn't upload a new version on Pypi

It runs with pip install from git, but there are other issues due to requirements (t5-large, I suppose).  I couldn't get any sample code to work. My m/c can support only upto t5-base. 

Anyway it will be good if you could add an Installation guide detailing all the requirements (python, gpu, etc.). Will be very useful for many.
